### ISSUE TITLE
Reduce to Anaconda & add Pycharm

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/python-ecology-lesson#1]
Update all setup instructions

- [-] remove Anaconda in favor of Miniconda
- [-] remove Jupyter in favor of PyCharm Edu
- [-] add config advice for PyCharm to use conda environment
- [-] instruct package install through PyCharm UI

**Comment by katrinleinweber** [comment]
No, too little time.

**Comment by katrinleinweber** [comment]
But enough time to use Anaconda & let _it_ install PyCharm!

**Comment by katrinleinweber** [comment]
@jkreklow: [IPython can be used from within PyCharm](https://programmingwithdan.com/python-tips-and-tricks/how-add-ipython-console-pycharm/) :-)

**Comment by katrinleinweber** [comment]
But [can't show plots inline](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002149279-Switching-to-inline-plots-in-the-Scientific-View-?page=1#community_comment_360000294300) :-(

**Comment by JuliaScheel** [comment]
Hey, sorry for the late reply. Personally I am used to Anaconda and Jupyter Notebook. If you think pycharm helps the students stick to studying, that I am happy to use it too :)

**Comment by katrinleinweber** [comment]
We can recommend PyCharm for further study, but because [it can't show plots in its iPython console](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002149279-Switching-to-inline-plots-in-the-Scientific-View-?page=1#community_comment_360000294300) it's out of the question for the workshop.

Spyder can, though.

**Comment by jkreklow** [comment]
I agree that we should recommend PyCharm, but use Anaconda at the workshop. What about the notebooks? I think they are particularly useful for working with DataFrames because of the much nicer output formatting and the more comfortable use of multiline code and we should introduce both - Jupyter for EDA and Spyder for storing and running the final code as scripts

**Comment by katrinleinweber** [comment]
I'm trying to install Spyder just now & it pushes a "Kite" extension into my system, and is throwing "Missing dependencies!" errors :-( Primarily Jupyter Notebooks, then.

**Comment by JuliaScheel** [comment]
Interesting. As previously stated I am quite happy with notebooks. Maybe you could show them PyCharm and some examples, how to navigate etc at the end of the course?

**Comment by katrinleinweber** [comment]
Yeah, except that lesson 1 introduces Spyder / IDEs already. I'll:

1. switch that to PyCharm,
1. briefly explain the differences,
1. then we use JN in the entire middle part.
